title: プログラミング
description: いつかゲーム開発を。
thumbnail: ./dev.avif

relatedSites:
  - title: Astro JS
    url: https://astro.build/
    description: Official Astro homepage. (temp)

  - title: Astro Docs
    url: https://docs.astro.build/